---
# tasks file for java

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags:
    - java

- include: java-home.yml

- include: CentOS.yml
  when: ansible_os_family == "RedHat"
  tags:
    - java

- include: Ubuntu.yml
  when: ansible_os_family == "Debian"
  tags:
    - java
